baseurl: "/wmo-voorspelmodel"
apiname: "WMO Voorwspelmodel Documentatie"
versie-nr: "1.0.7"
restAPI-Alternatief: "Nee"
url: "http://localhost:4000"
title: Wmo Voorspelmodel - Voorspelling Wmo gebruikers voor de komende 5 jaar

# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Wmo Voorspelmodel
    subnav:
      - title: Home
        path: /
      - title: Themas
        path: /themas
      - title: API Documentatie
        path: /docs 
      - title: Contact
        path: /contact

apinav:
  - title: API Documentatie
    subnav:
      - title: Home
        path: /
      - title: API 
        path: /API/
 

themanav:
  - title: Thema Navigatie
    subnav:
      - title: Home
        path: /
      - title: Thema
        path: /themas/


plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: vng-realisatie/jekyll-theme-vngrealisatie-kcdenm

github: vng-realisatie/wmo-voorspelmodel

theme: jekyll-theme-time-machine

project_name: VNG-Realisatie/WMO Voorspelmodel

standard_family: WSJG
